Bundler 1 no longer works on Ruby 3.2
* Specifically it fails due to:
ruby-3.2.2/lib/ruby/gems/3.2.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:272:in `search_up': undefined method `untaint' for "truffleruby/test/truffle/gems/bundler-version/one":String (NoMethodError)

      current  = File.expand_path(SharedHelpers.pwd).untaint
                                                    ^^^^^^^^
	from ruby-3.2.2/lib/ruby/gems/3.2.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:259:in `find_file'
	from ruby-3.2.2/lib/ruby/gems/3.2.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:251:in `find_gemfile'
	from ruby-3.2.2/lib/ruby/gems/3.2.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:60:in `in_bundle?'
	from ruby-3.2.2/lib/ruby/gems/3.2.0/gems/bundler-1.17.3/lib/bundler/setup.rb:5:in `<top (required)>'