Fix Exception#full_message when given cause with empty backtrace
The issue leads to the following error:

```
NameError: undefined local variable or method `exception' for module Truffle::ExceptionOperations
<internal:core> core/truffle/exception_operations.rb:319:in `append_causes'
<internal:core> core/truffle/exception_operations.rb:270:in `full_message'
<internal:core> core/exception.rb:81:in `full_message'
```