Fix instrumentation of WriteLocalVariableNode under AssignRescueVariableNode
* Revealed by TCK tests failing like this:
  java.lang.IllegalStateException: WrapperNode implementation org.truffleruby.language.RubyNodeWrapper
  cannot be safely replaced in parent node class org.truffleruby.core.rescue.AssignRescueVariableNode.