C++ extensions do not work with the old g++ system compiler on OL7 and Ubuntu 16.04
* The error is:
  /test/truffleruby-standalone/lib/cext/include/ruby/backward/cxxanyargs.hpp:98:69: error: 'std::nullptr_t' has not been declared
  rb_define_virtual_variable(const char *q, rb_gvar_getter_t *w, std::nullptr_t e)
* HAVE_NULLPTR is defined to 1 in all platform config files,
  because of using newer CC/CXX in PATH when running the CRuby ./configure script.
* On OL7 it should be possible to install devtoolset to address this, like documented in
  https://github.com/oracle/graal/blob/master/docs/getting-started/graalvm-enterprise/oci/installation-compute-instance-with-OL.md#oracle-linux-7
  However it seems messy and OL7 is EOL soon anyway.