Do not redefine memcpy
* It causes issues with C++ code like:
In file included from mini_racer_extension.cc:5:
In file included from
mxbuild/truffleruby-jvm/jre/languages/ruby/lib/gems/gems/libv8-7.3.492.27.1-x86_64-linux/vendor/v8/include/v8.h:21:
In file included from
mxbuild/truffleruby-jvm/jre/lib/llvm/bin/../include/c++/v1/memory:657:
mxbuild/truffleruby-jvm/jre/lib/llvm/bin/../include/c++/v1/utility:973:5:
error: no member named 'ruby_nonempty_memcpy' in namespace 'std'; did you mean
simply 'ruby_nonempty_memcpy'?
    std::memcpy(&__r, __p, sizeof(__r));
    ^~~~~
mxbuild/truffleruby-jvm/jre/languages/ruby/lib/cext/include/ruby/ruby.h:1956:1:
note: 'ruby_nonempty_memcpy' declared here
ruby_nonempty_memcpy(void *dest, const void *src, size_t n)
^