Use the 'P' specifier for PRIsVALUE
* Necessary to avoid -Wformat warnings by clang which assumes %Y is a char* specifier:
ossl_engine.c:523:9: error: format specifies type 'char *' but the argument has type 'VALUE' (aka 'unsigned long') [-Werror,-Wformat]
                      rb_obj_class(self), ENGINE_get_id(e), ENGINE_get_name(e));
                      ^~~~~~~~~~~~~~~~~~
1 error generated.